name: sysmac_events_generator
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.14.3 <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.19.2
dependencies: 
  archive: ^3.1.6
  collection: ^1.15.0
  fluent_regex: ^1.0.1
  xml: ^5.3.1
